openapi: 3.0.0
info:
  title: ms-core-openapi
  description: API for Core
  contact:
    name: Leva Dokhoyan
    email: dokhoyan-leva@mail.ru
  version: '1.0'
servers:
  - url: 'http://localhost:3000/api/v1'
    variables: { }
tags:
#  - name: 1
#  - name: 2
paths:

    404:
      description: Not found